all:
  hosts:
    master:
      ansible_host: 10.0.12.3
      ip: 10.0.12.3
      access_ip: 10.0.12.3
      ansible_user: a-xplat
    worker:
      ansible_host: 10.0.12.4
      ip: 10.0.12.4
      access_ip: 10.0.12.4
      ansible_user: a-xplat
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
