all:
  vars:
   ansible_ssh_private_key_file: /home/a-xplat/.ssh/id_rsa
  hosts:
    master:
      ansible_host: 10.0.11.5
      ip: 10.0.11.5
      access_ip: 10.0.11.5
      ansible_user: a-xplat
    worker:
      ansible_host: 10.0.11.6
      ip: 10.0.11.6
      access_ip: 10.0.11.6
      ansible_user: a-xplat
  children:
    kube_control_plane:
      hosts:
        master:
    kube_node:
      hosts:
        worker:
    etcd:
      hosts:
        master:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
