all:
  hosts:
    node1:
      ansible_host: 172.16.1.175
      ip: 172.16.1.175
      access_ip: 172.16.1.175
      ansible_user: a-xplat
    node2:
      ansible_host: 172.16.1.180
      ip: 172.16.1.180
      access_ip: 172.16.1.180
      ansible_user: a-xplat
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
